# Generated by Django 6.1.1 on 2026-09-14 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique company identifier, for example EMP-001.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use 3-20 letters, numbers or hyphens (for example EMP-001).', regex='^[A-Za-z0-9\\-]{3,20}$')], verbose_name='employee ID')),
                ('full_name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, for example +91 98765 43210.', regex='^\\+?[0-9\\s\\-]{7,20}$')])),
                ('address', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Design', 'Design'), ('Customer Support', 'Customer Support')], max_length=40)),
                ('designation', models.CharField(max_length=80)),
                ('date_of_joining', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, help_text='Annual gross salary.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'), models.Index(fields=['employment_status'], name='employees_e_employm_b2a249_idx')],
            },
        ),
    ]
